// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onhofhdkodkatefscpqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uaG9maGRrb2RrYXRlZnNjcHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NDQzMDksImV4cCI6MjA4NjUyMDMwOX0.UGPahBwJsbarojVCmfaycIOI3eh_AoAmykMggl9Dq2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});